services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    # Thêm cấu hình DNS của Google vào đây để Docker tìm thấy MongoDB Atlas
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules